// Mocks generated by Mockito 5.4.6 from annotations
// in afinz_app/test/features/balance/mocks/mock_balance_remote_datasource.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:afinz_app/features/balance/data/datasources/balance_remote_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BalanceRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBalanceRemoteDatasource extends _i1.Mock
    implements _i2.BalanceRemoteDatasource {
  MockBalanceRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> getBalance() =>
      (super.noSuchMethod(
            Invocation.method(#getBalance, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
